<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTkWZoYh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTkWZoYh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTkWZoYh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTkWZoYh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTkWZoYh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TkWZoYh',
    'container.build_id' => 'b8291d54',
    'container.build_time' => 1527144149,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTkWZoYh');
